Repository cartesi/cli, pull requests merged in 2024-10, with the labels that each got.

#102 SDK with devnet v2
  .changeset/orange-deers-refuse.md
  packages/sdk/docker-bake.hcl
Labels: v2

#103 Remove send dapp-address
  .changeset/early-ants-yell.md
  apps/cli/src/baseCommand.ts
  apps/cli/src/commands/send/dapp-address.ts
Labels: v2

#105 Bump CLI sdk
  .changeset/blue-planes-develop.md
  apps/cli/src/commands/build.ts
  apps/cli/src/node/docker-compose-anvil.yaml
  apps/cli/src/node/docker-compose-bundler.yaml
  apps/cli/src/node/docker-compose-paymaster.yaml
  packages/mock-verifying-paymaster/docker-compose.yaml
Labels: v2

#108 fix: workaround assert rolling template
  .changeset/pretty-terms-beam.md
  packages/sdk/create_machine_snapshot
Labels: sdk, v2

#113 refactor(tests): use DEFAULT_SDK
  apps/cli/src/config.ts
  apps/cli/test/builder/directory.test.ts
  apps/cli/test/builder/docker.test.ts
  apps/cli/test/builder/empty.test.ts
  apps/cli/test/builder/tar.test.ts
  apps/cli/test/exec/cartesi-machine.test.ts
  apps/cli/test/exec/crane.test.ts
  apps/cli/test/exec/genext2fs.test.ts
  apps/cli/test/exec/mksquashfs.test.ts
Labels: v2

#73 cli: enforce build for linux/riscv64 platform
  .changeset/big-ghosts-rescue.md
  apps/cli/src/builder/docker.ts
  apps/cli/test/builder/data/Dockerfile.nonriscv
  apps/cli/test/builder/docker.test.ts
Labels: cli, v2
